### ISSUE TITLE
License discrepancies in several sources files 

### ISSUE THREAD

**Issue by martian111** [joval/jOVAL#10]
Per the README, 

> To encourage adoption by third-parties, the jOVAL project is now licensed using the LGPL.

However, I found several source files with AGPL license headers:
./scap/schemas/joval/diagnostic-schema-1.0.xsd:  This software is licensed under the AGPL 3.0 license available at http://www.joval.org/agpl_v3.txt
./scap/schemas/ocil-2.0/ocil-diagnostic-schema.xsd:  This software is licensed under the AGPL 3.0 license available at http://www.joval.org/agpl_v3.txt
./scap/schemas/ocil-2.0/ocil-variables-schema.xsd:  This software is licensed under the AGPL 3.0 license available at http://www.joval.org/agpl_v3.txt
./scap-extensions/schemas.cat:This software is licensed under the AGPL 3.0 license available at http://www.joval.org/agpl_v3.txt

Are those intended to stay as AGPL or should they be updated as well?

Thanks!

**Comment by joval** [comment]
That was an oversight; I've corrected those references just now, thanks!

**Comment by martian111** [comment]
Great, Thank you!!
