### ISSUE TITLE
Error compiling jOVAL on both CentOS and Ubuntu

### ISSUE THREAD

**Issue by djmundus** [joval/jOVAL#9]
I'm trying to run make to get jOVAL compiled.  I get the following error on both Ubuntu and CentOS:

make[1]: Entering directory `/opt/joval/scap'  
mkdir -p build/META-INF  
sed 's/<bindings scd=\"x-schema::tns\"/<bindings scd=\"x-schema::tns\" if-exists=\"true\"/' schemas.episode > build/META-INF/sun-jaxb.episode  
sed: can't read schemas.episode: No such file or directory  
make[1]: *** [resources] Error 2  
make[1]: Leaving directory`/opt/joval/scap'  
make: **\* [/opt/joval/scap/scap-schema-1.2.jar] Error 2  

What am I missing?

**Comment by joval** [comment]
Do you happen to be at the Cybersecurity Innovation Conference in DC right now? If so, I can take a look in person.

**Comment by djmundus** [comment]
Nope…  I’m in Oakland, CA.

 

I’m giving a presentation at the Splunk conference on how to integrate free security tools into Splunk.  I’d love to cover jOVAL since it is multi-platform and has a commercial version if they want to do remote scanning.

 

The deadline for getting the presentation in is Friday AM, so I’d like to get it working by then if possible…

 

If you want to do a webex at some point, let me know.

 

C

**Comment by joval** [comment]
Shoot me an email at solin at jovalcm dot com and we'll sync up.

**Comment by bk007work** [comment]
> I'm trying to run make to get jOVAL compiled. I get the following error on both Ubuntu and CentOS:
> 
> make[1]: Entering directory `/opt/joval/scap' mkdir -p build/META-INF sed 's/<bindings scd=\"x-schema::tns\"/<bindings scd=\"x-schema::tns\" if-exists=\"true\"/' schemas.episode > build/META-INF/sun-jaxb.episode sed: can't read schemas.episode: No such file or directory make[1]: *** [resources] Error 2 make[1]: Leaving directory`/opt/joval/scap' make: *** [/opt/joval/scap/scap-schema-1.2.jar] Error 2
> 
> What am I missing?

How to solve this problem
